apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-be-app
  namespace: argocd
spec:
  project: app1-project
  source:
<<<<<<< HEAD
    repoURL: https://github.com/SrinivasNairTP/argocd-app1-backendendconfig.git
=======
    repoURL: https://github.com/SrinivasNairTP/argocd-app1-backend
>>>>>>> 2ac5cc3 (Fix backend application path)
    targetRevision: HEAD
    path: bacend
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
